services:
  api:
    build: ./api
    environment:
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_SECURE: ${COOKIE_SECURE}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_started
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    environment: {}
